// This file is auto generated
// Use `npm run code-generate:images` to update this file
export type ImageAssets = Readonly<
  Record<
    | 'autoBattleSwitchOff'
    | 'cancelButton'
    | 'closeButton'
    | 'cloverButton'
    | 'cloverPage'
    | 'continueButtonBlue'
    | 'continueButtonRed'
    | 'enemyLegend'
    | 'ex'
    | 'exWhite'
    | 'findTeam'
    | 'giveUpButtonBlue'
    | 'giveUpButtonWhite'
    | 'levelSelect'
    | 'levelSelectBeginner'
    | 'levelSelectExpert'
    | 'levelSelectMaster'
    | 'levelSelectStandard'
    | 'loadingText'
    | 'lv29Button'
    | 'menuButton'
    | 'nextBattleBlue'
    | 'nextText'
    | 'noContinueButton'
    | 'not4pplStart'
    | 'okButton'
    | 'presentButton'
    | 'presentPrice0'
    | 'presentPrice1500'
    | 'presentPrice15000'
    | 'presentPrice4000'
    | 'presentPrice8000'
    | 'rareItem'
    | 'repeatBattleButton'
    | 'repeatWithStaminaButton'
    | 'retryButtonBlue'
    | 'retryButtonRed'
    | 'startBattleButton'
    | 'stillStartButton'
    | 'stillStartButtonRed'
    | 'supportSelectButton'
    | 'supportSkillAvailable'
    | 'tapButton'
    | 'teamReadyButton'
    | 'transformGaugeFull'
    | 'x0',
    Image
  >
>;
