import {ITimeline} from "@/assets/timeline/type";
export const timeline_gaofeng: Record<string, ITimeline> = {};


timeline_gaofeng.a = { name: "后跳", time: 10 };
timeline_gaofeng.b = { name: "三角暴风", time: 13 };
timeline_gaofeng.c = { name: "前冲", time: 19 };
timeline_gaofeng.d = { name: "转身", time: 21 };
timeline_gaofeng.e = { name: "后跳", time: 25 };
timeline_gaofeng.f = { name: "三风点名", time: 29 };
timeline_gaofeng.g = { name: "全屏风", time: 36 };
timeline_gaofeng.h = { name: "红圈点名", time: 41 };
timeline_gaofeng.i = { name: "裂空域", time: 47 };
timeline_gaofeng.j = { name: "前冲", time: 52 };
timeline_gaofeng.k = { name: "转身", time: 55 };
timeline_gaofeng.l = { name: "三风点名", time: 58 };
timeline_gaofeng.m = { name: "后跳", time: 68 };
timeline_gaofeng.n = { name: "三角暴风", time: 72 };
timeline_gaofeng.o = { name: "前冲", time: 77 };
timeline_gaofeng.p = { name: "转身", time: 80 };
timeline_gaofeng.q = { name: "三风点名", time: 83 };
timeline_gaofeng.r = { name: "全屏风", time: 90 };
timeline_gaofeng.s = { name: "前冲", time: 98 };
timeline_gaofeng.t = { name: "转身", time: 100 };
timeline_gaofeng.u = { name: "召唤伙伴", time: 104 };
timeline_gaofeng.v = { name: "三风点名", time: 106 };
timeline_gaofeng.w = { name: "前冲", time: 112 };
timeline_gaofeng.x = { name: "转身", time: 114 };
timeline_gaofeng.y = { name: "后跳", time: 124 };
timeline_gaofeng.z = { name: "三角暴风", time: 127 };
timeline_gaofeng.aa = { name: "前冲", time: 133 };
timeline_gaofeng.ab = { name: "转身", time: 135 };
timeline_gaofeng.ac = { name: "全屏风", time: 137 };
timeline_gaofeng.ad = { name: "三风点名", time: 142 };
timeline_gaofeng.ae = { name: "后跳", time: 153 };
timeline_gaofeng.af = { name: "疾风弹", time: 156 };
timeline_gaofeng.ag = { name: "前冲", time: 169 };
timeline_gaofeng.ah = { name: "转身", time: 172 };
timeline_gaofeng.ai = { name: "后跳", time: 179 };
timeline_gaofeng.aj = { name: "三风点名", time: 183 };
timeline_gaofeng.ak = { name: "全屏风", time: 189 };
timeline_gaofeng.al = { name: "红圈点名", time: 193 };
timeline_gaofeng.am = { name: "裂空域", time: 199 };
timeline_gaofeng.an = { name: "三角暴风", time: 207 };
timeline_gaofeng.ao = { name: "前冲", time: 216 };
timeline_gaofeng.ap = { name: "转身", time: 218 };
timeline_gaofeng.aq = { name: "疾风弹2号，单吃", time: 222 };
timeline_gaofeng.ar = { name: "红圈点名", time: 226 };
timeline_gaofeng.as = { name: "裂空域", time: 233 };
timeline_gaofeng.at = { name: "三风点名", time: 239 };
timeline_gaofeng.au = { name: "全屏风", time: 246 };
timeline_gaofeng.av = { name: "前冲", time: 250 };
timeline_gaofeng.aw = { name: "转身", time: 253 };
timeline_gaofeng.ax = { name: "全屏风", time: 260 };

Object.freeze(timeline_gaofeng);
