import {ITimelineMore} from "@/assets/timeline/type";
export const timeline_gaofeng: Record<string, ITimelineMore> = {};


timeline_gaofeng.a = { name: "后跳", time: {minute: 4, second: 49} };
timeline_gaofeng.b = { name: "三角暴风", time: {minute: 4, second: 46} };
timeline_gaofeng.c = { name: "前冲", time: {minute: 4, second: 40} };
timeline_gaofeng.d = { name: "转身", time: {minute: 4, second: 38} };
timeline_gaofeng.e = { name: "后跳", time: {minute: 4, second: 34} };
timeline_gaofeng.f = { name: "三风点名", time: {minute: 4, second: 30} };
timeline_gaofeng.g = { name: "全屏风", time: {minute: 4, second: 23} };
timeline_gaofeng.h = { name: "红圈点名", time: {minute: 4, second: 18} };
timeline_gaofeng.i = { name: "裂空域", time: {minute: 4, second: 12} };
timeline_gaofeng.j = { name: "前冲", time: {minute: 4, second: 7} };
timeline_gaofeng.k = { name: "转身", time: {minute: 4, second: 4} };
timeline_gaofeng.l = { name: "三风点名", time: {minute: 4, second: 1} };
timeline_gaofeng.m = { name: "后跳", time: {minute: 3, second: 51} };
timeline_gaofeng.n = { name: "三角暴风", time: {minute: 3, second: 47} };
timeline_gaofeng.o = { name: "前冲", time: {minute: 3, second: 42} };
timeline_gaofeng.p = { name: "转身", time: {minute: 3, second: 39} };
timeline_gaofeng.q = { name: "三风点名", time: {minute: 3, second: 36} };
timeline_gaofeng.r = { name: "全屏风", time: {minute: 3, second: 29} };
timeline_gaofeng.s = { name: "前冲", time: {minute: 3, second: 21} };
timeline_gaofeng.t = { name: "转身", time: {minute: 3, second: 19} };
timeline_gaofeng.u = { name: "召唤伙伴", time: {minute: 3, second: 15} };
timeline_gaofeng.v = { name: "三风点名", time: {minute: 3, second: 13} };
timeline_gaofeng.w = { name: "前冲", time: {minute: 3, second: 7} };
timeline_gaofeng.x = { name: "转身", time: {minute: 3, second: 5} };
timeline_gaofeng.y = { name: "后跳", time: {minute: 2, second: 55} };
timeline_gaofeng.z = { name: "三角暴风", time: {minute: 2, second: 52} };
timeline_gaofeng.aa = { name: "前冲", time: {minute: 2, second: 46} };
timeline_gaofeng.ab = { name: "转身", time: {minute: 2, second: 44} };
timeline_gaofeng.ac = { name: "全屏风", time: {minute: 2, second: 42} };
timeline_gaofeng.ad = { name: "三风点名", time: {minute: 2, second: 37} };
timeline_gaofeng.ae = { name: "后跳", time: {minute: 2, second: 26} };
timeline_gaofeng.af = { name: "疾风弹", time: {minute: 2, second: 23} };
timeline_gaofeng.ag = { name: "前冲", time: {minute: 2, second: 10} };
timeline_gaofeng.ah = { name: "转身", time: {minute: 2, second: 7} };
timeline_gaofeng.ai = { name: "后跳", time: {minute: 2, second: 0} };
timeline_gaofeng.aj = { name: "三风点名", time: {minute: 1, second: 56} };
timeline_gaofeng.ak = { name: "全屏风", time: {minute: 1, second: 50} };
timeline_gaofeng.al = { name: "红圈点名", time: {minute: 1, second: 46} };
timeline_gaofeng.am = { name: "裂空域", time: {minute: 1, second: 40} };
timeline_gaofeng.an = { name: "三角暴风", time: {minute: 1, second: 32} };
timeline_gaofeng.ao = { name: "前冲", time: {minute: 1, second: 23} };
timeline_gaofeng.ap = { name: "转身", time: {minute: 1, second: 21} };
timeline_gaofeng.aq = { name: "疾风弹2号，单吃", time: {minute: 1, second: 17} };
timeline_gaofeng.ar = { name: "红圈点名", time: {minute: 1, second: 13} };
timeline_gaofeng.as = { name: "裂空域", time: {minute: 1, second: 6} };
timeline_gaofeng.at = { name: "三风点名", time: {minute: 1, second: 0} };
timeline_gaofeng.au = { name: "全屏风", time: {minute: 0, second: 53} };
timeline_gaofeng.av = { name: "前冲", time: {minute: 0, second: 49} };
timeline_gaofeng.aw = { name: "转身", time: {minute: 0, second: 46} };
timeline_gaofeng.ax = { name: "全屏风", time: {minute: 0, second: 39} };

Object.freeze(timeline_gaofeng);
