# encoding: utf-8

import os
import pandas as pd
import codecs


pwd = os.getcwd()

out = codecs.open('autogenerated.ts', 'wb', encoding='utf-8')
input_file = 'D:\\dragalia-dbm\\src\\assets\\timeline\\timeline_gaofeng.csv'

data = ()
start_time = '4:59'

def translate_time(start_time, end_time):

    start_min, start_sec = [int(x) for x in start_time.split(':')[:2]]
    end_min, end_sec = [int(x) for x in end_time.split(':')[:2]]
    if start_sec >= end_sec:
        sec_dif = start_sec - end_sec
        min_dif = start_min - end_min
    else:
        sec_dif = start_sec+60 - end_sec
        min_dif = start_min - end_min -1 
    return min_dif*60 + sec_dif


# file head
out.write("""
interface ITimeline {
  name: string;
  time: number;
}""" + '\n')

out.write('export const index: Record<string, ITimeline> = {};\n')
x = pd.read_csv(input_file, header=None).values.tolist()

i = 1
for line in x:
    skill_name = line[0]
    time = line[1]
    trans_time = translate_time(start_time, time)
    outline = 'index\.{} = \{'.format(str(i))
    outline1 = 'name: \"{}\", time: {}\};\n'.format(skill_name, str(trans_time))
    #outline = 'index.123123 = \{ name\: \"dddd\", time: 123\};\n'
    out.write(outline)
    i += 1

out.write('\nObject.freeze(index);\n')
    
        


    
